### ISSUE TITLE
OOM error 

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [otenim/Xception#1]
@otenim Is there any option to control GPU OOM error ?. Because in have only 4 GB

**Comment by otenim** [comment]
@NarasimmanSaravana1994 

The easiest way is to reduce the batch size.
The default batch sizes during pre-training stage and fine-tuning stage are set to 32 and 16, respectively. I recommend you to try halving them; please add `--batch_size_pre 16` and `--batch_size_fine 8` options when executing fine_tune.py.

Be sure that reducing batch sizes affects the training result.
I think it would get worse little bit, but you never know until you try it :)

**Comment by NarasimmanSaravana1994** [comment]
@otenim  right now I'm doing this approach only.
Thanks for the reply.
